public class HalilPractise {
    public void printMessage(string mes,string mes2,string mes3) {
        system.debug('this is my parametr: '+ mes + mes3);
        system.debug('also parametr: '+mes2);
    }

    public void add(integer a,integer b) {
        integer sumOfInteger = 0;
        sumOfInteger = a+b;
        system.debug('the sum is : '+sumOfInteger);

   }

   public integer add(integer a,integer b);
}
