public  class MathematicalClass {
    public integer addition (integer num1 ,integer num2) {
       integer total =  num1 + num2;
       return total;
    }

    public integer substraction (integer num1, integer num2) {
        integer total = num2-num1;
        return total;
    }

    public integer multiplication (integer num3, integer num4) {
        integer total = num3 * num4;
        return total;
    }

    public integer division (integer num3, integer num4) {
        integer total = num3 / num4;
        return total;
    }
}
