MathematicalClass obj = new MathematicalClass();

integer  result1 = obj.addition(5, 6);
system.debug('Addition result is : ' + result1);

integer result2 = obj.substraction(8, 3);
system.debug('Substraction result is '+ result2);

integer result3 = obj.multiplication(2, 9);
system.debug('Multiplication result is ' + result3);

integer result4 = obj.division(10, 5);
system.debug('Division result is '+ result4);